module.exports.descriptors = [
    "Albert's",
    "Alberto's",
    "Blake's",
    "Bonnie's",
    "Carla's",    
    "Charlie's",
    "Donnie's",    
    "Daphne's",
    "Denny's",
    "Erick's",
    "Ethan's",
    "Frank's",
    "Giovanni's",
    "George's",
    "Henry's",
    "Hank's",
    "Iggy's",
    "Ivan's",
    "Jeoffrey's",
    "John's",
    "Kevin's",
    "Karen's",
    "Mike's",
    "Manny's",
    "Mary's",
    "Montgomery's",
    "Nick's",
    "Nancy's",
    "Nathan's",
    "Olive's",
    "Orville's",
    "Pete's",
    "Paul's",
    "Ralph's",
    "Robert's",
    "Raul's",
    "Sammy's",
    "Sam's",
    "Tom's",
    "Tommy's",
    "Tammy's",
    "Whitney's"
];

module.exports.types = [
    "Bar",
    "Barista",
    "Pizza Grotto",
    "Burger Lounge",
    "Taco Castle",
    "Steakhouse",
    "Seafood Dine-in",
    "Buffet",
    "Mediterranean Cuisine",
    "Mexican Food",
    "Chinese Food",
    "Tai Cuisine",
    "Italian Restaurant",
    "HotDog Heaven",
    "Golden Coral",
    "Chronic Burgers",
    "CrazyHorse Buffet",
    "Mongolian Grill",
    "Barbeque",
    "American Grill",
    "Chinese Cuisine",
    "Taco Lounge",
    "Burger Joint",
    "Big Burger",
    "Chronic Tacos",
    "Ice Cream Parlor",
    "Taco Lounge",
    "Breakfast Inn",
    "Cuban Food",
    "Puertorican Food",
    "French Bakery",
    "Japanese Steakhouse",
    "American Diner",
    "Chinese Bakery",
    "Authentic Arabic Food",
    "Pizza Parlor",
    "Spagetti Factory",
    "Seafood and Steakhouse",
    "Seafood Cuisine",
    "Brunch Cafe",
];